WITH REF_STG_CERIF_RESEARCH_AREA AS (SELECT * FROM {{ ref('STG_CERIF_RESEARCH_AREA') }})
SELECT AIRFLOW.UDF_MD5_HASH([RESEARCH_AREA_CODE]) AS RESEARCH_AREA_SID,
       RESEARCH_BRANCH_CODE,
       RESEARCH_BRANCH_NAME,
       RESEARCH_SUBBRANCH_CODE,
       RESEARCH_SUBBRANCH_NAME,
       RESEARCH_AREA_CODE,
       RESEARCH_AREA_NAME
FROM REF_STG_CERIF_RESEARCH_AREA
UNION ALL
SELECT 'n/a' AS RESEARCH_AREA_SID,
       'n/a' AS RESEARCH_BRANCH_CODE,
       'n/a' AS RESEARCH_BRANCH_NAME,
       'n/a' AS RESEARCH_SUBBRANCH_CODE,
       'n/a' AS RESEARCH_SUBBRANCH_NAME,
       'n/a' AS RESEARCH_AREA_CODE,
       'n/a' AS RESEARCH_AREA_NAME