CREATE OR REPLACE TABLE `collaboration-recommender`.AIRFLOW.CERIF_RESEARCH_AREA
(
    RESEARCH_BRANCH_CODE    STRING,
    RESEARCH_BRANCH_NAME    STRING,
    RESEARCH_SUBBRANCH_CODE STRING,
    RESEARCH_SUBBRANCH_NAME STRING,
    RESEARCH_AREA_CODE     STRING,
    RESEARCH_AREA_NAME     STRING
);
