CREATE OR REPLACE TABLE DATALAKE.CROSSREF_HISTORIC_ARTICLE_EUTOPIA AS
SELECT DISTINCT DOI
FROM DATALAKE.CROSSREF_HISTORIC_ARTICLE
         LEFT JOIN UNNEST(JSON_EXTRACT_ARRAY(JSON, '$.author')) AS AUTHOR_JSON ON TRUE
         LEFT JOIN UNNEST(JSON_EXTRACT_ARRAY(AUTHOR_JSON, '$.affiliation')) AS AFFILIATION_JSON ON TRUE
WHERE DATALAKE.UDF_IS_EUTOPIA_AFFILIATED_STRING(JSON_EXTRACT_SCALAR(AFFILIATION_JSON, '$.name'))