CREATE OR REPLACE TABLE `collaboration-recommender`.AIRFLOW.EUTOPIA_INSTITUTION
(
    INSTITUTION_SID          STRING,
    INSTITUTION_NAME         STRING,
    INSTITUTION_PRETTY_NAME  STRING,
    INSTITUTION_COUNTRY      STRING,
    INSTITUTION_LANGUAGE     STRING,
    INSTITUTION_COUNTRY_ISO2 STRING
);
