CREATE OR REPLACE PROCEDURE ANALYTICS.SP_FILL_TEXT_EMBEDDING_ARTICLE_GECKO()
BEGIN
    DECLARE ROW_COUNT INT64;
    DECLARE NEW_ROW_COUNT INT64;
    -- Save the number of rows in the table
    SET ROW_COUNT = (SELECT COUNT(1) FROM ANALYTICS.TEXT_EMBEDDING_ARTICLE_GECKO);

    CREATE OR REPLACE TEMPORARY TABLE MISSING_TEXT_EMBEDDING_ARTICLE_GECKO AS
    SELECT A.EMBEDDING_INPUT AS CONTENT, A.ARTICLE_DOI
    FROM PROD.STG_EMBEDDING_ARTICLE A
             LEFT JOIN ANALYTICS.TEXT_EMBEDDING_ARTICLE_GECKO TE
                       ON A.ARTICLE_DOI = TE.DOI
    WHERE TE.DOI IS NULL;

    -- Insert statement
    INSERT INTO ANALYTICS.TEXT_EMBEDDING_ARTICLE_GECKO
        (DOI, EMBEDDING_TENSOR_DATA)
    SELECT T.ARTICLE_DOI    AS DOI,
           T.TEXT_EMBEDDING AS EMBEDDING_TENSOR_DATA
    FROM ML.GENERATE_TEXT_EMBEDDING(
                 MODEL ANALYTICS.MODEL_TEXT_EMBEDDING_GECKO,
                 (SELECT A.CONTENT, A.ARTICLE_DOI
                  FROM MISSING_TEXT_EMBEDDING_ARTICLE_GECKO A)
         ) T;

    -- Save the number of rows in the table
    SET NEW_ROW_COUNT = (SELECT COUNT(1) FROM ANALYTICS.TEXT_EMBEDDING_ARTICLE_GECKO);

    -- Return the number of new rows
    SELECT NEW_ROW_COUNT - ROW_COUNT AS NEW_ROWS_COUNT;
END;