CREATE OR REPLACE TABLE ANALYTICS.TEXT_EMBEDDING_RESEARCH_AREA_TOP_N_ARTICLES_GECKO AS
SELECT T.TEXT_EMBEDDING AS EMBEDDING_TENSOR_DATA,
       T.ARTICLE_DOI    AS DOI,
       T.RESEARCH_AREA_CODE
FROM ML.GENERATE_TEXT_EMBEDDING(
             MODEL `collaboration-recommender`.ANALYTICS.MODEL_TEXT_EMBEDDING_GECKO,
             (SELECT EMBEDDING_INPUT AS CONTENT, RESEARCH_AREA_CODE, ARTICLE_DOI
              FROM DBT_DEV.EMBEDDING_RESEARCH_AREA_TOP_N_ARTICLES)
     ) T;

