CREATE OR REPLACE TABLE `collaboration-recommender`.ANALYTICS.TEXT_EMBEDDING_RESEARCH_TOPIC
(
    RESEARCH_AREA_CODE    STRING,
    EMBEDDING_TENSOR_SHAPE ARRAY <INT64>,
    EMBEDDING_TENSOR_DATA  ARRAY <FLOAT64>
);




