CREATE
OR REPLACE TABLE ANALYTICS.TEXT_EMBEDDING_ARTICLE_GECKO AS
SELECT T.TEXT_EMBEDDING AS EMBEDDING_TENSOR_DATA,
       T.ARTICLE_DOI    AS DOI
FROM ML.GENERATE_TEXT_EMBEDDING(
             MODEL `collaboration-recommender`.ANALYTICS.MODEL_TEXT_EMBEDDING_GECKO,
             (SELECT EMBEDDING_INPUT AS CONTENT, ARTICLE_DOI FROM DBT_DEV.EMBEDDING_ARTICLE LIMIT 10000)
     ) T;


-- Insert statement
INSERT INTO ANALYTICS.TEXT_EMBEDDING_ARTICLE_GECKO
    (DOI, EMBEDDING_TENSOR_DATA)
SELECT T.ARTICLE_DOI    AS DOI,
       T.TEXT_EMBEDDING AS EMBEDDING_TENSOR_DATA
FROM ML.GENERATE_TEXT_EMBEDDING(
             MODEL `collaboration-recommender`.ANALYTICS.MODEL_TEXT_EMBEDDING_GECKO,
             (SELECT A.EMBEDDING_INPUT AS CONTENT, A.ARTICLE_DOI
              FROM DBT_DEV.EMBEDDING_ARTICLE A
                       LEFT JOIN ANALYTICS.TEXT_EMBEDDING_ARTICLE_GECKO TE
                                 ON A.ARTICLE_DOI = TE.ARTICLE_DOI
              WHERE TE.ARTICLE_DOI IS NULL
                 LIMIT 100)
     ) T;


ALTER TABLE ANALYTICS.TEXT_EMBEDDING_ARTICLE_GECKO
    RENAME COLUMN TEXT_EMBEDDING TO EMBEDDING_TENSOR_DATA;

ALTER TABLE ANALYTICS.TEXT_EMBEDDING_ARTICLE_GECKO
    RENAME COLUMN ARTICLE_DOI TO DOI;
