WITH REF_STG_CERIF_RESEARCH_AREA AS (SELECT *
                                     FROM {{ source('AIRFLOW', 'CERIF_RESEARCH_AREA') }})
SELECT RESEARCH_BRANCH_CODE,
       RESEARCH_BRANCH_NAME,
       RESEARCH_SUBBRANCH_CODE,
       RESEARCH_SUBBRANCH_NAME,
       RESEARCH_AREA_CODE,
       RESEARCH_AREA_NAME
FROM REF_STG_CERIF_RESEARCH_AREA