WITH SRC_CROSSREF_HISTORIC_ARTICLE AS (SELECT *
                                       FROM {{ source('DATALAKE', 'CROSSREF_HISTORIC_ARTICLE') }}),
     SRC_CROSSREF_HISTORIC_ARTICLE_EUTOPIA AS (SELECT *
                                               FROM {{ source('DATALAKE', 'CROSSREF_HISTORIC_ARTICLE_EUTOPIA') }})
SELECT DISTINCT S.DOI,
                AUTHOR_INDEX,
                S.JSON AS SOURCE_JSON,
                AUTHOR_JSON,
                AFFILIATION_JSON
FROM SRC_CROSSREF_HISTORIC_ARTICLE S
         INNER JOIN SRC_CROSSREF_HISTORIC_ARTICLE_EUTOPIA EUTOPIA USING (DOI)
         LEFT JOIN UNNEST(JSON_EXTRACT_ARRAY(JSON, '$.author')) AS AUTHOR_JSON WITH
OFFSET AS AUTHOR_INDEX
ON TRUE
    LEFT JOIN UNNEST(JSON_EXTRACT_ARRAY(AUTHOR_JSON, '$.affiliation')) AS AFFILIATION_JSON ON TRUE