WITH REF_STG_CROSSREF_RESEARCH_AREA_TOP_N_ARTICLES AS (SELECT *
                                                       FROM {{ source('AIRFLOW', 'CROSSREF_RESEARCH_AREA_TOP_N_ARTICLES') }})
SELECT RESEARCH_AREA_CODE
     , JSON_EXTRACT(JSON, '$.DOI')      AS ARTICLE_DOI
     , JSON_EXTRACT(JSON, '$.title')    AS ARTICLE_TITLE
     , JSON_EXTRACT(JSON, '$.abstract') AS ARTICLE_ABSTRACT
FROM REF_STG_CROSSREF_RESEARCH_AREA_TOP_N_ARTICLES