WITH REF_STG_COLLABORATION AS (SELECT *
                               FROM {{ref('STG_COLLABORATION')}}),
     REF_STG_CROSSREF_AUTHOR AS (SELECT *
                                 FROM {{ref('STG_CROSSREF_AUTHOR')}})
SELECT INITIAL_AUTHOR.AUTHOR_SID            AS INITIAL_AUTHOR_SID,
       NEIGHBOR_AUTHOR.AUTHOR_SID           AS NEIGHBOR_AUTHOR_SID,
       DIM_INITIAL_AUTHOR.AUTHOR_FULL_NAME  AS INITIAL_AUTHOR_FULL_NAME,
       DIM_NEIGHBOR_AUTHOR.AUTHOR_FULL_NAME AS NEIGHBOR_AUTHOR_FULL_NAME
FROM REF_STG_COLLABORATION INITIAL_AUTHOR
         INNER JOIN REF_STG_COLLABORATION NEIGHBOR_AUTHOR
                    ON INITIAL_AUTHOR.ARTICLE_SID = NEIGHBOR_AUTHOR.ARTICLE_SID
                        AND INITIAL_AUTHOR.AUTHOR_SID < NEIGHBOR_AUTHOR.AUTHOR_SID
         INNER JOIN REF_STG_CROSSREF_AUTHOR DIM_INITIAL_AUTHOR
                    ON INITIAL_AUTHOR.AUTHOR_SID = DIM_INITIAL_AUTHOR.AUTHOR_SID
         INNER JOIN REF_STG_CROSSREF_AUTHOR DIM_NEIGHBOR_AUTHOR
                    ON NEIGHBOR_AUTHOR.AUTHOR_SID = DIM_NEIGHBOR_AUTHOR.AUTHOR_SID
GROUP BY INITIAL_AUTHOR.AUTHOR_SID,
         NEIGHBOR_AUTHOR.AUTHOR_SID,
         DIM_INITIAL_AUTHOR.AUTHOR_FULL_NAME,
         DIM_NEIGHBOR_AUTHOR.AUTHOR_FULL_NAME