WITH REF_STG_CROSSREF_DOI_METADATA AS (SELECT *
                                       FROM {{ ref('STG_CROSSREF_HISTORIC_ARTICLE_FINAL') }})
SELECT DISTINCT AUTHOR_SID,
                AUTHOR_FULL_NAME,
                AUTHOR_ORCID_ID
FROM REF_STG_CROSSREF_DOI_METADATA
